#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$#" -eq 0 ]; then
  for t in "$ROOT"/tests/*.xc; do
    xc $t "$@" -O0 -o a.out && ./a.out || exit 1
  done
else
  xc "$ROOT"/tests/"$1"_test.xc -o a.out "${@:2}" && ./a.out || exit 1
fi
